### ISSUE TITLE
Ensure core.async is hidden from clients

### ISSUE THREAD

**Issue by mdallastella** [7bridges-eu/shelob#5]
See 7bridges-eu/harvester#2

**Comment by manuel-uberti** [comment]
We need to make sure everything concerning asynchronous operations via `core.async` is managed in `shelob`.

`shelob` should offer its clients facilities to:

- execute functions of any given arity asynchronously
- formalise a structure to pass the functions to execute, and in which order (e.g., a vector of functions can be enough, since `core.async` channels accept functions as inputs too)
- collect the results once all the functions passed to `shelob` are done

**Comment by skuro** [comment]
"any given arity" seems too much to me. I'd go for some specific "callbacks" of a sort, for which shelob can mandate the signature. In general, clients should be able to perform the following operations when it comes to scraping (which seems to me to be the first and foremost use case for async behavior, feel free to correct me if you think otherwise):

- initialize each scraper (e.g. login / set cookies / etc)
- process one URL (e.g. via a callback)
- process a failure (e.g. via another callback)
- potentially feed extra URL as a result of processing (i.e. crawl the page)
- keep track of the scraping status (e.g. `url-queue-size` vs `url-processed-count`)
- forcibly halt the whole machinery

does it make sense?

**Comment by manuel-uberti** [comment]
Sort of :)

What do you mean by "callback"? Can you give an example (pseudo-code is totally fine) of `client<->shelob` interaction according to your description?

**Comment by skuro** [comment]
I specifically avoided getting into the API details before we agreed on principles :-)
I'll put together some initial draft ideas of how the above might work. I used the term `callback` as a generic term for "plain functions to be executed by shelob" along the processing pipeline. Quite similar to your "execute functions of any given arity asynchronously" requirement, although in my brain the arity might be mandated by shelob APIs which is why I chose to use the term "callback", IMHO more representative of this approach.

To be continued

**Comment by skuro** [comment]
Alright, I thought a bit about it and I think the following is what makes the most sense to me. IMHO a few major knobs need to be provided:

- control how a URL is *browsed*, i.e. how to go from URL to content. This is where Selenium Drivers are managed and used to retrieve content (a mix of `navigate-fn` and `init-fn`)
- define the *parsing* so that users can extract data from content (similar in scope to `scrape-fn`)
- expose *management* capabilities to e.g. inspect progress and forcibly stop the whole process

## Browsing

In this step we need to materialize a Selenium Driver and drive it to a URL. I don't think that managing the Selenium Driver lifecycle within Shelob is feasible, as we've seen that things like changing proxy configuration requires creating a new driver instance, so users need to be in control of that. What I have in mind is a reducing-fn signature such as:

```clojure
(defn browse [ctx url]
  (if (shelob/abort? ctx)
    (reduced ctx)                                        ;; reduced contexts shortcut the overall operation
    (let [driver (obtain-selenium-driver ctx)]           ;; `obtain-selenium-driver` is user-provided
      (assoc ctx :document-content (browse-page url))))) ;; `browse-page` is user-provided
```

## Parsing

Here we have to extract the data we want from a document content. This step feels to me really like a reducing step, so that each step incorporates the result of a parsing action into an accumulator. Something like:

```clojure
(defn parse [ctx content]                               ;; `ctx` is the same as what's passed to `browse`, content `content` is the actual output of a `browse` action
  (if (shelob/abort? ctx)
    (reduced ctx)                                       ;; reduced values shortcut the overall operation
    (update ctx :result conj (parse-content content)))) ;; `parse-content` is user-provided
```

## Progress and management

This is where we put everything together when we kickstart Shelob: we need to return a value that enables introspection. This value is almost necessarily a deref, some mutable thingie that gets updated by the previous steps, à la:

```clojure
(defn go [urls]
  (let [ongoing-process (shelob/run! browse parse urls)]
    (Thread/sleep 10000)
    (when (not (shelob/done? @ongoing-process))
      (println "Not done in 10s, aborting:" (shelob/progress @ongoing-process))
      (shelob/abort! @ongoing-process))))
```

The above hides concurrency completely, leaving all of the internal shelob machinery amenable to `core.async` or whatever concurrency system without affecting downstream code.

## Closing thoughts

Given the above APIs, shelob would be ensuring that any output of `browse` is fed into `parse`, regardless of the concurrency model. One feature that I didn't explore yet, but that the above model should support by virtue of the context, is the ability to add extra URLs to the process along the way (i.e. support crawling). This could be a specific keyword on the context that can be processed by shelob at the end of any `browse` and `parse` step.

Thoughts?

**Comment by manuel-uberti** [comment]
Sorry for the late reply, I was on holiday last week.

IIUC, your idea is leaving `shelob` only in charge of process management. Right now, `shelob` provides:

- initialization of the driver and control over its state (cfr. `shelob.core/close-pool`)
- browsing facilities (in terms of wrappers around Selenium operations)
- scraping facilities (leveraging Jsoup)

Basically you intend to leave controlling over the driver state, browsing and scraping to the user, am I correct?

**Comment by skuro** [comment]
Shelob might provide something to actually create the drivers, but I would appreciate a more fine-grained set of functions rather than a facility that encapsulates all of the init logic. Or maybe both, but with high degrees of configurability for the end user in terms of 

a) *when* the driver is created and destroyed
b) *how* the driver is configured upon creation

re: browsing facilities they are more than welcome, here i was just commenting on the async ops / driver management capabilities

re: scraping facilities, same as above, more than welcome to stay

**Comment by mdallastella** [comment]
> a) _when_ the driver is created and destroyed
> b) _how_ the driver is configured upon creation

Can be enough if we put the driver initialization options inside the context (so they can be eventually changed at runtime) and shelob provides some sort of `reset` function that reinitialize the driver(s)?

For example, in the context we can have a `:driver-options` key which contains all the proper options (like proxy settings, profile, headless and so on).

The `reset` function than have just to close all the old webdriver instances and create a new pool using the `:driver-options` settings.

This operation can be done anytime the user wants.

**Comment by skuro** [comment]
My current use case (and it can actually be more of a corner case) is to make sure I can dynamically change the proxy configuration of the drivers, e.g. use a fresh new proxy after 10 browsing actions. This currently requires the creation of a brand new `Driver` instance. As far as I can see, @mdallastella approach of having a `reset` function could even be overkill for me, instead of which I could use something like

```clojure
(reset! driver)
```
to mean that the specific `Driver` should not be reused anymore and thus evicted from the pool (could then be called `evict!` -- maybe together with a 0-arity `evict-all!`?) 

----- EDIT

The above would require that `:driver-options` is not a static map of values but something dynamic, since I would have to generate / pick the new proxy at every `Driver` creation. A function would help more than a map in this case.

**Comment by manuel-uberti** [comment]
Fixed on branch `dev` by https://github.com/7bridges-eu/shelob/commit/1c9d52fb180e5c4ac2663c1b5cb94daac85c2111.
